# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: setup
  password: secret123

development:
  <<: *default
  database: todo-list-api_development

test:
  <<: *default
  database: todo-list-api_test

staging:
  <<: *default
  database: todo-list-api_staging

production:
  <<: *default
  database: todo-list-api_production
